version: "3.7"

services:
#  api_service:
#    image: borischen0203/my-app-image
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - mysql_db

  mysql_db:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: url_shorter_service
#      MYSQL_USER: java_to_dev
#      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: password
